version: '3.8'

services:
  nfclistener:
    container_name: nfclistener
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/bus/usb:/dev/bus/usb/003/003
    restart: always
    privileged: true
