export type ParticipantType = {
  tn_id: number,
  tn_created_at?: string,
  tn_nachname?: string,
  tn_vorname?: string,
  tn_afanummer?: string,
  tn_adresse?: string,
  tn_plz?: string,
  tn_ort?: string,
  tn_geburtstag?: string,
  tn_inaktiv: boolean,
  tn_modifikator: number,
  tn_kt_art?: string,
  tn_kt_bezeichnung?: string,
  tn_kt_plz?: string,
  tn_kt_ort?: string,
  tn_kt_sb_nachname?: string,
  tn_kt_sb_vorname?: string,
  tn_kt_sb_anrede?: string,
  tn_kt_sb_briefanrede?: string,
  tn_zweifelhaft: boolean,
  tn_kt_adresse?: string,
  tn_email_intern?: string,
  tn_email_extern?: string,
  tn_kt_sb_email?: string,
  tn_test: boolean,
  tn_client_id?: string,
  tn_created_by?: string,
  tn_edited_at?: string,
  tn_edited_by?: string,
  tn_rfid?: string,
}

export type PresenceType = {
  anw_id?: number;
  anw_created_at?: string,
  anw_datum: string,
  anw_tn_id: number,
  anw_von_uhrzeit?: number,
  anw_bis_uhrzeit?: number,
  anw_topic?: string,
  anw_modifikator: number,
  anw_home_office?: boolean,
  anw_art?: string,
  anw_client_id: string,
  anw_created_by?: string,
  anw_edited_at?: string,
  anw_edited_by?: string,
  anw_checked?: boolean,
}