export type UserType = {
  tn_id: number,
  tn_created_at: string | null,
  tn_nachname: string | null,
  tn_vorname: string | null,
  tn_afanummer: string | null,
  tn_adresse: string | null,
  tn_plz: string | null,
  tn_ort: string | null,
  tn_geburtstag: string | null,
  tn_inaktiv: boolean,
  tn_modifikator: number,
  tn_kt_art: string | null,
  tn_kt_bezeichnung: string | null,
  tn_kt_plz: string | null,
  tn_kt_ort: string | null,
  tn_kt_sb_nachname: string | null,
  tn_kt_sb_vorname: string | null,
  tn_kt_sb_anrede: string | null,
  tn_kt_sb_briefanrede: string | null,
  tn_zweifelhaft: boolean,
  tn_kt_adresse: string | null,
  tn_email_intern: string | null,
  tn_email_extern: string | null,
  tn_kt_sb_email: string | null,
  tn_test: boolean,
  tn_client_id: string | null,
  tn_created_by: string | null,
  tn_edited_at: string | null,
  tn_edited_by: string | null,
  tn_rfid: string | null,
}

export type PresenceType = {
  anw_id: number | null;
  anw_created_at: string | null,
  anw_datum: string,
  anw_tn_id: number,
  anw_von_uhrzeit: number | null,
  anw_bis_uhrzeit: number | null,
  anw_topic: string | null,
  anw_modifikator: number,
  anw_home_office: boolean | null,
  anw_art: string | null,
  anw_client_id: string,
  anw_created_by: string | null,
  anw_edited_at: string | null,
  anw_edited_by: string | null,
  anw_checked: boolean | null,
}